---
title: "SRT411A0"
author: "Joy Chowdhury"
date: "January 30, 2017"
output: 
  html_document:
    keep_md: true
---

<h4 style="color:red;">ToDo1</h4>
```{r}
(2017-2016)/(2017-1995)*100
```

<h4 style="color:red;">ToDo2</h4>
```{r}
college.years <- 2017-2016
life.years <- 2017-1995
percentage.college.life <- college.years/life.years*100
```

<h4 style="color:red;">ToDo3</h4>
```{r}
sum(c(4, 5, 8, 11))
```

<h4 style="color:red;">ToDo4</h4>
```{r}
plot(rnorm(100))
```

<h4 style="color:red;">ToDo5</h4>
```{r}
help(sqrt)
```

<h4 style="color:red;">ToDo6</h4>
```{r}
file.create("firstscript.R")
writeLines(text = "plot(rnorm(100))", con = "firstscript.R")
source("firstscript.R")
source("firstscript.R")
source("firstscript.R")
source("firstscript.R")
source("firstscript.R")
```

<h4 style="color:red;">ToDo7</h4>
```{r}
matrix(seq(from = 31, to = 60, length.out = 30), nrow = 6, ncol = 5)
```

<h4 style="color:red;">ToDo8</h4>
```{r}
file.create("ToDo8.R")
writeLines("x1 = rnorm(100)
           x2 = rnorm(100)
           x3 = rnorm(100)
           t = data.frame(a = x1, b = x1 + x2, c = x1 + x2 + x3)
           plot(t, ask = F)
           print(sd(unlist(t)))", con = "ToDo8.R", sep="\n")
source("ToDo8.R")
#The results show several scatter plot diagrams of all the possible permutations between the three
#axial values.  The standard deviation can only read unlisted vectors so the data frame must be
#unlisted.  It represents the degree of variance among all the elements in the data frame.
source("ToDo8.R")
source("ToDo8.R")
source("ToDo8.R")
source("ToDo8.R")
```

<h4 style="color:red;">ToDo9</h4>
```{r}
file.create("ToDo9.R")
writeLines("x1 = rnorm(100)
           x2 = rnorm(100)
           x3 = rnorm(100)
           t = data.frame(a = x1, b = x1 + x2, c = x1 + x2 + x3)
           plot(t$a, type = 'l', ylim = range(t), lwd = 3, col = rgb(1, 0, 0, 0.3))
           lines(t$b, type = 's', lwd = 2, col = rgb(0.3,0.4,0.3,0.9))
           points(t$c, pch = 20, cex = 4, col = rgb(0, 0, 1, 0.3))", con = "ToDo9.R", sep = "\n")
source("ToDo9.R")
#rgb stands for red green blue primaries which are colour specifications for a certain object.
#The object is coloured corresponding to the given intensity of each primary.
#The last arguement of rgb is alpha, which is are semi-transparent colours that are supported
#by only some devices.
#lwd is the line width, defaulting to 1.
#pch is the plotting character/symbol to use for each point.  The integer refers to a graphics symbol.
#cex is the arguement for character expansion that sets the scale for the symbol specified by pch.
```

<h4 style="color:red;">ToDo10</h4>
```{r}
file.create("tst1.txt")
write.table(data.frame(a = c(1, 2, 4, 8, 16, 32), 
                       g = c(2, 4, 8, 16, 32, 64), 
                       x = c(3, 6, 12, 24, 48, 96)), file = "tst1.txt", row.names = F)
d <- read.table(file = "tst1.txt", header = TRUE)
d$g <- d$g * 5
write.table(d, file = "tst2.txt", row.names = F)
```

<h4 style="color:red;">ToDo11</h4>
```{r}
mean(sqrt(rnorm(100)))
#NaN values are produced among some of the elements because the a square root of a negative was calculated.
```

<h4 style="color:red;">ToDo12</h4>
```{r}
dates = strptime(c("20170130", "20171101", "20171230"), format = "%Y%m%d")
num.presents = c(0, 1, 0)
barplot(num.presents, names.arg = dates)
```

<h4 style="color:red;">ToDo13</h4>
```{r}
vect <- 1:100
for (i in 1:100) {
  if (vect[i] < 5 | vect[i] > 90) {
    vect[i] <- vect[i] * 10
  } else {
    vect[i] <- vect[i] * 0.1
  }
}
vect
```

<h4 style="color:red;">ToDo14</h4>
```{r}
CalculateNewVector <- function(vx) {
  for (i in vx[1]:length(vx)) {
    if (vx[i] < 5 | vx[i] > 90) {
      vx[i] <- vx[i] * 10
    } else {
      vx[i] <- vx[i] * 0.1
    }
  }
  return(vx)
}
```

<h4 style="color:red;">ToDoFootNote</h4>
```{r}
CalculateNewVector <- function(vect) {
  return(ifelse((vect < 5 | vect > 90),vect*10,vect*0.1))
}
```